version: '3.7'
services:
  nginx:
    build: nginx
    ports:
      - '8080:8080'
    depends_on:
      - django
  django:
    build: django
    command: poetry run uwsgi /app/uwsgi.ini
    volumes:
      - ./django:/app
    environment:
      APP_DIR: '/app'
